version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/JlecHuk5/kafka-go"
  dependencies_vendored = true

[[transformers]]
name = "gofmt"

[[transformers]]
name = "gofumpt"